name = "emoji-worker"
workers_dev = true
compatibility_date = "2022-07-09"
main = "build/worker/shim.mjs"

kv_namespaces = [
    { binding = "EMOJIS", id = "4b23aec72b6d44be8c5f809df07ce404", preview_id = "51e84f3be8a3401e991f774ed515431b" }
]

[vars]
WORKERS_RS_VERSION = "0.0.9"

[build]
command = "cargo install -q worker-build && worker-build --release" # required

# read more about configuring your Worker via wrangler.toml at:
# https://developers.cloudflare.com/workers/cli-wrangler/configuration
